### ISSUE TITLE
"MODULE FAILURE" while configuring frr for a simple task using frr.frr.frr_bgp

### ISSUE THREAD

**Issue by gabrielmorin1** [ansible-collections/frr.frr#64]
##### SUMMARY
Hello,

When trying to add a simple BGP configuration for FRR using this ansible collection, I encounter a "MODULE FAILURE" error.

I described my environment and error encountred below.

In advance, thanks for your help.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

frr.frr.frr_bgp

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.2]
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/gabriel/.local/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/lib/python3.10/dist-packages/ansible_collections
Collection Version
---------- -------
frr.frr    2.0.2
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /root/.ansible.cfg
DEFAULT_HOST_LIST(/root/.ansible.cfg) = ['/root/.ansible-hosts']
```

##### OS / ENVIRONMENT

QEMU virtualized Ubuntu 22.04 LTS, latest updates, FRR 8.0

##### STEPS TO REPRODUCE

`ansible-playbook frr_configure.yml` on a new frr install. Only thing modified is the `bgpd=yes` instead of `bgpd=no` in the `/etc/frr/deamon` file.

```yaml
---
- name: configure frr
  hosts: all
  remote_user: root
  
  tasks:
    - name: Configure global AS6500
      frr.frr.frr_bgp:
        config:
          bgp_as: 6500
        operation: merge
```

##### EXPECTED RESULTS

I exected to have no errors and see the line `router bgp 6500` in my frr running config.

##### ACTUAL RESULTS

Got the error below :

```paste below
TASK [Configure global AS6500] *****************************************************************************************
task path: /root/frr_sandbox/install_frr.yml:26
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851 `" && echo ansible-tmp-1702992302.1149354-2831-5370698501851="` echo /root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/frr/frr/plugins/modules/frr_bgp.py
<localhost> PUT /root/.ansible/tmp/ansible-local-2199hog7_q77/tmp7d_zjc0y TO /root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/ /root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.frr.frr.plugins.modules.frr_bgp', init_globals=dict(_module_fqn='ansible_collections.frr.frr.plugins.modules.frr_bgp', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_frr.frr.frr_bgp_payload_yu7t2mk4/ansible_frr.frr.frr_bgp_payload.zip/ansible_collections/frr/frr/plugins/modules/frr_bgp.py", line 486, in <module>
  File "/tmp/ansible_frr.frr.frr_bgp_payload_yu7t2mk4/ansible_frr.frr.frr_bgp_payload.zip/ansible_collections/frr/frr/plugins/modules/frr_bgp.py", line 472, in main
  File "/tmp/ansible_frr.frr.frr_bgp_payload_yu7t2mk4/ansible_frr.frr.frr_bgp_payload.zip/ansible_collections/frr/frr/plugins/module_utils/network/frr/providers/module.py", line 26, in __init__
  File "/tmp/ansible_frr.frr.frr_bgp_payload_yu7t2mk4/ansible_frr.frr.frr_bgp_payload.zip/ansible/module_utils/connection.py", line 124, in __init__
AssertionError: socket_path must be a value
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1702992302.1149354-2831-5370698501851/AnsiballZ_frr_bgp.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.frr.frr.plugins.modules.frr_bgp', init_globals=dict(_module_fqn='ansible_collections.frr.frr.plugins.modules.frr_bgp', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_frr.frr.frr_bgp_payload_yu7t2mk4/ansible_frr.frr.frr_bgp_payload.zip/ansible_collections/frr/frr/plugins/modules/frr_bgp.py\", line 486, in <module>\n  File \"/tmp/ansible_frr.frr.frr_bgp_payload_yu7t2mk4/ansible_frr.frr.frr_bgp_payload.zip/ansible_collections/frr/frr/plugins/modules/frr_bgp.py\", line 472, in main\n  File \"/tmp/ansible_frr.frr.frr_bgp_payload_yu7t2mk4/ansible_frr.frr.frr_bgp_payload.zip/ansible_collections/frr/frr/plugins/module_utils/network/frr/providers/module.py\", line 26, in __init__\n  File \"/tmp/ansible_frr.frr.frr_bgp_payload_yu7t2mk4/ansible_frr.frr.frr_bgp_payload.zip/ansible/module_utils/connection.py\", line 124, in __init__\nAssertionError: socket_path must be a value\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by lunarthegrey** [comment]
Same issue here.
